"""add tags_directorys table

Revision ID: 45bc88e6b52d
Revises: db5e31a0233d
Create Date: 2026-04-28 17:50:37.111918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bc88e6b52d'
down_revision = 'db5e31a0233d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_directorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tags_directorys_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags_directorys')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('tags_directorys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_directorys_project_id'), ['project_id'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags_directorys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_directorys_project_id'))

    op.drop_table('tags_directorys')
    # ### end Alembic commands ###
