"""add tag_tags_directorys_column

Revision ID: c04102f5eddc
Revises: 45bc88e6b52d
Create Date: 2026-04-28 18:48:44.945768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04102f5eddc'
down_revision = '45bc88e6b52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags_directory_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tags_tags_directory_id'), ['tags_directory_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_tags_tags_directory_id_tags_directorys'), 'tags_directorys', ['tags_directory_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_tags_directory_id_tags_directorys'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tags_tags_directory_id'))
        batch_op.drop_column('tags_directory_id')

    # ### end Alembic commands ###
